### ISSUE TITLE
Wayland session unavailable

### ISSUE THREAD

**Issue by enx1998** [hhfeuer/Gentoo-Gnome-3.36-X#2]
Hi hhfeuer,
after upgrading gnome using this repo I cannot use wayland session but only x11 one: for example gdm tries to start with wayland support but after a minute or so it fallbacks to x11.
I have the same behavior whith another installation I've done on another pc.
Do you have any suggestion on how to solve the problem?

Thanks ENx

P.S.: I already installed `>=wayland-protocols-1.19`

**Comment by hhfeuer** [comment]
Anything in dmesg/journalctl/coredumpctl?

**Comment by enx1998** [comment]
Hei hhfeuer,
sorry for the late replay, attached gdm debug start log.
Thanks ENx
[gdb_debug_log.txt](https://github.com/hhfeuer/Gentoo-Gnome-3.36-X/files/4465425/gdb_debug_log.txt)

**Comment by Nordicruler** [comment]
+1 no wayland session

**Comment by hhfeuer** [comment]
Please post the output of
emerge -pv gdm gnome-shell

**Comment by Nordicruler** [comment]
emerge -pv gdm gnome-shell

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] gnome-base/gnome-shell-3.36.1::Gnome-3-36-X  USE="browser-extension ibus networkmanager systemd -bluetooth (-elogind) -gtk-doc -telepathy -test" PYTHON_SINGLE_TARGET="python3_8 -python3_6 -python3_7" 0 KiB
[ebuild   R    ] gnome-base/gdm-3.34.1::Gnome-3-36-X  USE="branding introspection tcpd wayland -accessibility -audit -fprint -ipv6 -plymouth (-selinux) -smartcard -test -xinerama" 0 KiB

**Comment by enx1998** [comment]
Hei hhfeuer,
these are the packages that will be merged:
```
Calculating dependencies... done!
[ebuild   R    ] gnome-base/gnome-shell-3.36.1::Gnome-3-36-X  USE="bluetooth browser-extension ibus networkmanager systemd (-elogind) -gtk-doc -telepathy -test" PYTHON_SINGLE_TARGET="python3_6 -python3_7 (-python3_8)" 0 KiB
[ebuild   R   ~] gnome-base/gdm-3.34.1::gentoo  USE="branding introspection ipv6 plymouth systemd tcpd wayland xinerama -accessibility -audit -bluetooth-sound (-elogind) -fprint (-selinux) -smartcard -test" 0 KiB
```

Thanks ENx

**Comment by hhfeuer** [comment]
I'm a bit lost here. Mutter+Wayland works just fine, I can easily start a wayland session. The problem seems to be with gnome-shell, it seems doesn't even tries to start a wayland session, it just ignores everything and goes right over to waiting to connect to an X session. So also no errors are reported.
I'll keep debugging this but it's a mystery to me right now.

**Comment by enx1998** [comment]
hi hhfeuer,
thanks for your work.
Can I help you in any way?

**Comment by hhfeuer** [comment]
Mystery solved. It wasn't gnome-shell that was waiting for an Xserver but atk/at-spi2-atk. Those packages have to be at least version 2.34 for wayland to work. Luckily, those packages have been unmasked in portage today, so just do a system upgrade.
I'm pushing a new ebuild for gnome-shell that raises that dependency.

**Comment by Nordicruler** [comment]
Thanks. Wayland session working as expected.

**Comment by enx1998** [comment]
Thanks a lot, now wayland session works! 
Thank you for your time.
ENx
